Fixed an error when listing all border violators. There was a problem with DateTimeFormat locale when switching to language to English.
java.lang.IllegalArgumentException: Illegal pattern character 'n'
	at java.text.SimpleDateFormat.compile(Unknown Source)
	...